
SELECT BECAS.CONVOCATORIA, BECAS.MODALIDAD, COUNT(BECARIOS.DNI) AS TOTAL
FROM BECAS 
INNER JOIN BECARIOS
ON BECAS.ID_BECA = BECARIOS.ID_BECA
GROUP BY BECAS.CONVOCATORIA, BECAS.MODALIDAD;

SELECT IES.IES_NOMBRE, BECAS.CONVOCATORIA, BECAS.CARRERA, BECARIOS.ESTADO_ACTUAL
FROM IES 
INNER JOIN BECAS
ON IES.ID_IES = BECAS.ID_IES
INNER JOIN BECARIOS
ON BECAS.ID_BECA = BECARIOS.ID_BECA;


SELECT IES.TIPO_IES, IES.TIPO_GESTION FROM IES;


UPDATE IES SET IES.TIPO_GESTION = 'PRIVADO', IES.TIPO_IES = 'UNIVERSIDAD';

SELECT IES_NOMBRE FROM IES;

SELECT ASESOR FROM ASESORES;


INSERT INTO daniel.asesores(id_asesor, asesor) VALUES (asesores_seq.nextval, 'Maribel'); -- change Camus

UPDATE IES
SET TIPO_IES = 'UNIVERSIDAD'
where TIPO_IES = 'UNVERSIDAD'

select * from ies;
SELECT * FROM ASESORES;

SELECT * FROM DB_BECARIOS_EXT;
SELECT COUNT(*) FROM DB_BECARIOS_EXT;


SELECT ASESOR, CONVOCATORIA, MODALIDAD, CARRERA, IES_NOMBRE, NOMBRES, ESTADO_ACTUAL
FROM BECARIOS 
INNER JOIN BECAS 
ON BECARIOS.ID_BECA = BECAS.ID_BECA 
INNER JOIN IES 
ON BECAS.ID_IES = IES.ID_IES 
INNER JOIN ASESORES
ON BECAS.ASESOR_RESPONSABLE = ASESORES.ID_ASESOR;