-- DROP TABLES
DROP TABLE BECA_BENEFICIOS;
DROP TABLE BENEFICIOS;
DROP TABLE PAGO_SUBVENCION;
DROP TABLE PAGO_ACADEMICO;
DROP TABLE TRAMITES;
DROP TABLE CONDICION_PAGO;
DROP TABLE BECARIOS;
DROP TABLE BECAS;
DROP TABLE ASESORES;
DROP TABLE IES;

-- DROP SEQUENCES
DROP SEQUENCE PAGO_SUBVENCION_SEQ;
DROP SEQUENCE PAGO_ACADEMICO_SEQ;
DROP SEQUENCE TRAMITES_SEQ;
DROP SEQUENCE CONDICION_PAGO_SEQ;
DROP SEQUENCE BECAS_SEQ;
DROP SEQUENCE BENEFICIOS_SEQ;
DROP SEQUENCE ASESORES_SEQ;
DROP SEQUENCE IES_SEQ;

-- CREATE TABLES
CREATE TABLE BECARIOS(
  DNI VARCHAR2(8) NOT NULL,
  APELLIDOS VARCHAR2(200) NOT NULL,
  NOMBRES VARCHAR2(200) NOT NULL,
  FECHA_NACIMIENTO DATE,
  EDAD NUMBER(3),
  SEXO VARCHAR2(30),
  NUMERO_EXPEDIENTE VARCHAR2(50),
  ID_BECA NUMBER(4),
  REPRESENTANTE VARCHAR2(255),
  REPRESENTANTE_DNI VARCHAR2(20),
  TELEFONOS VARCHAR2(100),
  CORREO_PRONABEC VARCHAR2(100),
  CORREO_PERSONAL VARCHAR2(100),
  DIRECCION VARCHAR2(200),
  REGION_PROCEDENCIA VARCHAR2(100),
  PROVINCIA_PROCEDENCIA VARCHAR2(100),
  DISTRITO_PROCEDENCIA VARCHAR2(100),
  REGION_POSTULACION VARCHAR2(100),
  PROVINCIA_POSTULACION VARCHAR2(100),
  DISTRITO_POSTULACION VARCHAR2(100),
  RESOLUCION_ADJUDICACION VARCHAR2(100),
  RESOLUCION_ADJUDICACION_FECHA DATE,
  ESTADO_ACTUAL VARCHAR2(100),
  OBSERVACIONES VARCHAR2(255)
);

CREATE TABLE BECAS(
  ID_BECA NUMBER(4) NOT NULL,
  CONVOCATORIA VARCHAR2(30),
  MODALIDAD VARCHAR2(200),
  ID_IES NUMBER(4),
  REGION_ESTUDIO VARCHAR2(100),
  SEDE_ESTUDIO VARCHAR2(100),
  CARRERA VARCHAR2(200),
  INICIO_BECA DATE,
  TERMINO_BECA DATE,
  SEMESTRE_EGRESO VARCHAR2(20),
  ASESOR_RESPONSABLE NUMBER(3)
);

CREATE TABLE IES(
  ID_IES NUMBER(4) NOT NULL,
  IES_NOMBRE VARCHAR2(200),
  TIPO_IES VARCHAR2(100),
  TIPO_GESTION VARCHAR2(100)
);

CREATE TABLE TRAMITES(
  ID_TRAMITE NUMBER(5) NOT NULL,
  DNI_BECARIO VARCHAR2(8) NOT NULL,
  NUMERO_SIGEDO VARCHAR2(20),
  MOTIVO VARCHAR2(255),
  OFICINA_DESTINO VARCHAR(200),
  ESTADO VARCHAR2(100),
  TIPO_DOC_RESPUESTA VARCHAR2(100),
  NUMERO_DOCUMENTO VARCHAR2(100),
  FECHA_DOCUMENTO DATE
);

CREATE TABLE BENEFICIOS(
  ID_BENEFICIO NUMBER(3) NOT NULL,
  DESCRIPCION VARCHAR2(200)
);

CREATE TABLE BECA_BENEFICIOS(
  ID_BECA NUMBER(4) NOT NULL,
  ID_BENEFICIOS NUMBER(3) NOT NULL
);

CREATE TABLE CONDICION_PAGO(
  ID_CONDICION_PAGO NUMBER(5)  NOT NULL,
  FECHA DATE,
  DNI_BECARIO VARCHAR2(8),
  ESTADO VARCHAR2(100),
  CONDICION_SIBEC VARCHAR2(100),
  SITUACION VARCHAR2(100),
  CONDICION_SUBVENCION VARCHAR2(100)
);

CREATE TABLE PAGO_ACADEMICO(
  ID_PAGO_ACADEMICO NUMBER(5) NOT NULL,
  NUMERO_CONVENIO VARCHAR2(100),
  MES VARCHAR2(30),
  NUMERO_CUOTA VARCHAR2(20),
  NUMERO_SOLICITUD VARCHAR2(50),
  FECHA_SOLICITUD DATE,
  NUMERO_CONFORMIDAD VARCHAR2(50),
  CANTIDAD_BECARIOS NUMBER,
  MONTO_TOTAL  NUMBER(8,2),
  PAGO_MATERIALES NUMBER(8,2)
);

CREATE TABLE PAGO_SUBVENCION(
  ID_PAGO_SUBVENCION NUMBER(5) NOT NULL,
  ID_BECA NUMBER(4),
  DNI_BECARIO VARCHAR2(8),
  MONTO_SUBVENCION NUMBER(8,2),
  MES VARCHAR2(30),
  SOLICITUD VARCHAR2(100),
  CONFORMIDAD VARCHAR2(100),
  MONTO_TOTAL NUMBER(8,2)
);

CREATE TABLE ASESORES(
  ID_ASESOR NUMBER(3) NOT NULL,
  ASESOR VARCHAR2(200)
);

-- CREATE PRIMARY AND FOREIGN KEYS 
ALTER TABLE ASESORES
ADD CONSTRAINT ASESORES_PK PRIMARY KEY (ID_ASESOR);

ALTER TABLE BECARIOS
ADD CONSTRAINT BECARIOS_PK PRIMARY KEY (DNI);

ALTER TABLE BECAS 
ADD CONSTRAINT BECAS_PK PRIMARY KEY (ID_BECA);

ALTER TABLE BECARIOS
ADD CONSTRAINT BECARIOS_FK_BECARIO FOREIGN KEY (ID_BECA)
REFERENCES BECAS (ID_BECA);

ALTER TABLE BECAS
ADD CONSTRAINT BECAS_FK_ASESORES FOREIGN KEY (ASESOR_RESPONSABLE)
REFERENCES ASESORES(ID_ASESOR);

ALTER TABLE BENEFICIOS 
ADD CONSTRAINT BENEFICIOS_PK PRIMARY KEY (ID_BENEFICIO);

ALTER TABLE BECA_BENEFICIOS
ADD CONSTRAINT BECA_BENEFICIOS_FK_BECA FOREIGN KEY (ID_BECA)
REFERENCES BECAS(ID_BECA);

ALTER TABLE BECA_BENEFICIOS
ADD CONSTRAINT BECA_BENEFICIOS_FK_BENEFICIO FOREIGN KEY (ID_BENEFICIOS)
REFERENCES BENEFICIOS (ID_BENEFICIO);

ALTER TABLE PAGO_SUBVENCION
ADD CONSTRAINT PAGO_SUBVENCION_PK PRIMARY KEY (ID_PAGO_SUBVENCION);

ALTER TABLE PAGO_SUBVENCION
ADD CONSTRAINT PAGO_SUBNVENCION_FK_BECARIO FOREIGN KEY (DNI_BECARIO)
REFERENCES BECARIOS(DNI);

ALTER TABLE TRAMITES
ADD CONSTRAINT TRAMITES_PK PRIMARY KEY (ID_TRAMITE);

ALTER TABLE TRAMITES
ADD CONSTRAINT TRAMITES_FK_BECARIO FOREIGN KEY (DNI_BECARIO)
REFERENCES BECARIOS(DNI);

ALTER TABLE CONDICION_PAGO
ADD CONSTRAINT CONDICION_PAGO_PK PRIMARY KEY (ID_CONDICION_PAGO);

ALTER TABLE CONDICION_PAGO
ADD CONSTRAINT CONDICION_PAGO_FK_BECARIO FOREIGN KEY (DNI_BECARIO)
REFERENCES BECARIOS(DNI);

ALTER TABLE IES
ADD CONSTRAINT IES_PK PRIMARY KEY (ID_IES);

ALTER TABLE BECAS
ADD CONSTRAINT BECAS_FK_IES FOREIGN KEY (ID_IES)
REFERENCES IES (ID_IES);

-- CREATE SEQUENCES
CREATE SEQUENCE BECAS_SEQ
MINVALUE 1
MAXVALUE 9999
START WITH 1
INCREMENT BY 1
CACHE 20;

CREATE SEQUENCE IES_SEQ
MINVALUE 1
MAXVALUE 9999
START WITH 1
INCREMENT BY 1
CACHE 20;

CREATE SEQUENCE TRAMITES_SEQ
MINVALUE 1
MAXVALUE 99999
START WITH 1
INCREMENT BY 1
CACHE 20;


CREATE SEQUENCE BENEFICIOS_SEQ
MINVALUE 1
MAXVALUE 999
START WITH 1
INCREMENT BY 1
CACHE 20;


CREATE SEQUENCE CONDICION_PAGO_SEQ
MINVALUE 1
MAXVALUE 99999
START WITH 1
INCREMENT BY 1
CACHE 20;


CREATE SEQUENCE PAGO_ACADEMICO_SEQ
MINVALUE 1
MAXVALUE 99999
START WITH 1
INCREMENT BY 1
CACHE 20;


CREATE SEQUENCE PAGO_SUBVENCION_SEQ
MINVALUE 1
MAXVALUE 99999
START WITH 1
INCREMENT BY 1
CACHE 20;


CREATE SEQUENCE ASESORES_SEQ
MINVALUE 1
MAXVALUE 999
START WITH 1
INCREMENT BY 1
CACHE 20;

-- Vistas
CREATE OR REPLACE VIEW vista_becas_estado
as
select  a.asesor, b.convocatoria, b.modalidad, i.ies_nombre, b.carrera,  bs.estado_actual, count(*) t_becarios
from becarios bs
inner join becas b
on bs.id_beca = b.id_beca
inner join ies i
on b.id_ies = i.id_ies
inner join asesores a
on b.asesor_responsable = a.id_asesor
group by a.asesor, b.convocatoria, b.modalidad, i.ies_nombre, b.carrera, bs.estado_actual
order by b.convocatoria, b.modalidad, i.ies_nombre, b.carrera, bs.estado_actual;